# Generated by Django 3.1.4 on 2021-02-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='app',
            field=models.FileField(default='', upload_to='AppTools'),
        ),
    ]
