# Generated by Django 3.1.6 on 2021-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTools', '0002_auto_20210206_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='app',
            field=models.FileField(default='', upload_to='Apks'),
        ),
    ]
