# Generated by Django 3.1.6 on 2021-02-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTools', '0003_auto_20210212_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='app',
            field=models.FileField(default='', upload_to='AppTools'),
        ),
    ]
